#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Feb 14 11:36:35 MYT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=16
shaderPack=ComplementaryReimagined_r2.2.zip
enableShaders=false
